apiVersion: v1
kind: Service
metadata:
  name: emailservice
  labels:
    app.kubernetes.io/name: emailservice
    app.kubernetes.io/part-of: online-boutique
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
    - name: grpc
      port: 5000
      targetPort: 8080
