apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  labels:
    app.kubernetes.io/name: currencyservice
    app.kubernetes.io/part-of: online-boutique
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
    - name: grpc
      port: 7000
      targetPort: 7000
