apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  labels:
    app.kubernetes.io/name: redis-cart
    app.kubernetes.io/part-of: online-boutique
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
