apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app.kubernetes.io/name: cartservice
    app.kubernetes.io/part-of: online-boutique
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
    - name: grpc
      port: 7070
      targetPort: 7070
