apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  labels:
    app.kubernetes.io/name: checkoutservice
    app.kubernetes.io/part-of: online-boutique
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
    - name: grpc
      port: 5050
      targetPort: 5050
